### ISSUE TITLE
panic: runtime error: slice bounds out of range

### ISSUE THREAD

**Issue by rlaakkol** [github/git-lfs#1005]
I'm doing a very big push operation (the same as in #999), and the pre push lfs transfers go on fine for a couple of hours, but at some point, this happens:
[errors2.txt](https://github.com/github/git-lfs/files/130235/errors2.txt)

Any ideas?

**Comment by technoweenie** [comment]
What does `git lfs version` show?

**Comment by rlaakkol** [comment]
git-lfs/1.1.1 (GitHub; linux amd64; go 1.4.2)

But this is actually a version where I have added those Waits to get rid of the zombies. But I did encounter this behaviour already with a version without those changes.

**Comment by technoweenie** [comment]
Thanks. Having the exact version ensures I'm looking in the right place. The problem is here on line 374: https://github.com/github/git-lfs/blob/05aa87dbf5c6c7feced04bb43c907cc3ba4e1f76/lfs/scanner.go#L368-L374:

For some reason, `git cat-file --batch-check` is returning a bad line. Maybe it's not reporting the size for some reason? Here's a diff that would print the bad line, if you have a way to replicate this easily:

```diff
diff --git a/lfs/scanner.go b/lfs/scanner.go
index 87abed1..0c0f866 100644
--- a/lfs/scanner.go
+++ b/lfs/scanner.go
@@ -371,6 +371,7 @@ func catFileBatchCheck(revs chan string) (chan string, error) {
                        // type is at a fixed spot, if we see that it's "blob", we can avoid
                        // splitting the line just to get the size.
                        if line[41:45] == "blob" {
+                               tracerx.Printf("BLOB: %q", line)
                                size, err := strconv.Atoi(line[46:len(line)])
                                if err != nil {
                                        continue
```

If you could help track it down, that'd be swell. If you just want to get on with your work, you could try out my fix at #1006 :)

**Comment by rlaakkol** [comment]
Awesome, thanks! I'll try to replicate it with the traces. I suppose I will need to set GIT_TRACE=1 for this trace to show? Or is there a way to show this with some less verbose debugging level?

**Comment by rlaakkol** [comment]
I think this was after all caused by my own changes (similar to #999). Sorry for the inconvenience! I'll try to create a better PR!

**Comment by technoweenie** [comment]
No worries. The code was too trusting of git's behavior, anyway.
