### ISSUE TITLE
Can't push all objects to a new server

### ISSUE THREAD

**Issue by rjbell4** [github/git-lfs#1018]
I changed the Git LFS server (by adding a .lfsconfig file), and I'm attempting to push all Git LFS objects to the new server.  I've done that with "git push --all origin *mybranchname*".  However, that fails verifying the uploaded object.

This is the diagnosis according to @technoweenie:
>so i think whats happening is that the file was updated multiple times, and it's blowing up in ensureFile() because the actual file in the working directory is the latest version
>which seems dumb. how would we not have run into this by now
>should be an easy fix though

Currently we have only 50 commits, so I'm working around this issue checking out each commit and running the push on each one individually.  That seems to be working.  However, if we were to attempt things after 10,000 commits (for example), that would not have been practical.

**Comment by technoweenie** [comment]
Well, the good news is that the issue is not nearly as bad as I thought. There's a guard clause [at the top of `ensureFile()`](https://github.com/github/git-lfs/blob/a2781ff9cd5c38d0662218412910cbd14d296ed7/lfs/upload_queue.go#L80-L85), that returns early if the clean path doesn't exist.

The "clean path" is the full path to the content addressable filename, like ".git/lfs/objects/87/4b/874bacb5f6771c4aa238ff5421cb20725cbdd8cd3a63b8f138a82622fb4d2848". Git LFS writes the object content here, and uploads it to the server.  In cases where you're trying to push content that didn't get cleaned properly, Git LFS will try to re-clean the file before blowing up.

So what happened in your case?

> Expected binaries/archive/cemgui-app-data-bearcat.tar.gz to have an OID of 4f59c25f8a76d601d12691097432475691fc836a4338eb716345c03f8d7f5658, got 874bacb5f6771c4aa238ff5421cb20725cbdd8cd3a63b8f138a82622fb4d2848

I think what happened is that you have a clone with only the latest version of "binaries/archive/cemgui-app-data-bearcat.tar.gz". As LFS is scanning commits to see what LFS objects it needs to upload, it found an older version of that file, with contents matching "4f59c25f8a76d601d12691097432475691fc836a4338eb716345c03f8d7f5658". For some reason, `.git/lfs/objects/4f/59/4f59c25f8a76d601d12691097432475691fc836a4338eb716345c03f8d7f5658` doesn't live in your local repository. So it tried to read the current contents of the file to build it, but the current version doesn't match the older version it's trying to upload.

While the error message is correct, it is confusing. The fix is to recreate `.git/lfs/objects/4f/59/4f59c25f8a76d601d12691097432475691fc836a4338eb716345c03f8d7f5658` somehow. Since you're migrating from one LFS server to another, simply run `git lfs fetch --all` to download everything from the old server. That should fill the missing file in.

> Currently we have only 50 commits, so I'm working around this issue checking out each commit and running the push on each one individually.

This works too, as running `git checkout` on each commit should download LFS objects from the origin remote.

While this isn't a _bug_, there are a couple things I'd like to do:

* Rewrite the error message to be more clear. It shouldn't take me this long to grok what's going on :)
* Ensure we're bubbling the error message up correctly. You shouldn't have to run a custom build with extra trace commands to get it.

**Comment by rjbell4** [comment]
Sounds good.  ```git lfs fetch --all``` is a reasonable thing to need to do.  Usability / diagnosibility issues can count as "bugs", too (or at least, "issues to be addressed"). :)

**Comment by technoweenie** [comment]
Yup, taken care of here: https://github.com/github/git-lfs/pull/1023

Thanks for the report!
