### ISSUE TITLE
How do I remove all files associated with a specific .git repository? 

### ISSUE THREAD

**Issue by TheYokai** [github/git-lfs#1043]
So I've been testing out Git-LFS for game development related needs and it seems pretty good, but there's a few issues I've been having.

I'm using GIT-LFS with a locally hosted GitLab server which contains all of the versioned content files. This is great, but when I remove remove a project from GitLab it will [apparently keep a lot of those files sitting around on my harddisk leading to wasted resources.](https://gitlab.com/gitlab-org/gitlab-ce/issues/3666)

For this reason, I've been trying to find if there's a way to remove all files associated with a git repository before I remove it from my repository server. This is kind of a deal breaker for our use case because game assets can take up a large amount of space and the idea of prototype builds taking up hard drive space while they are no longer being managed is just not feasible on our (relatively) small hard drives. 

So my question: Is there a way to completely remove all LFS objects associated with a specific .git repository? Or maybe even (ideally) a way to archive them temporarily? I tried navigating to my LFS object container folder in hopes that the files would first be sorted by project, and then by hex pointer ids, but it turns out that there's not a single human readable folder there for managing the files associated with a specific git repository. Would lfs purge remove files that are no longer referenced by any .git repository?

**Comment by technoweenie** [comment]
You can run `git lfs prune` to remove objects from your local `.git/lfs/objects` directory. Here are the rules it uses to decide what to delete: https://github.com/github/git-lfs/blob/master/docs/man/git-lfs-prune.1.ronn

**Comment by TheYokai** [comment]
I may understand this incorrectly, but git prune only seems good when it comes to removing old files that exist in previous commits. This is useful, but it doesn't help with removing all files associated with a specific project.

Unless, of course, I could untrack all of the objects, add them to a git ignore instead, commit, and then prune to remove all the objects that existed previously?

**Comment by technoweenie** [comment]
Currently, LFS expects there to be objects to go with all of the blobs that you checkout. So currently, the only way to deal with this is rebasing your repository (https://help.github.com/articles/remove-sensitive-data/), and hoping your LFS server has a way to purge the objects.

I can see this being rather inconvenient though. This actually came up a couple times talking to devs at GDC a couple weeks ago. I have some ideas on a proposal that I'll post soon. I'd like to get some feedback from you though.

1. How would you, as a user, want to purge LFS objects? 
  * Would you purge a specific version of a file?
  * Would you purge ALL versions of a file?
  * Would you want to purge a range of versions? Maybe keep weekly checkpoints of active files or something.
2. Do you want the ability to set policies on files, file types, or directories?
  * Keep `n` versions of a file.
  * Keep periodic (daily/weekly/monthly) checkpoints of files
3. What would you expect Git LFS to do if it can't download a file that's been purged?
  * Pointer file
  * Nothing
4. What would you expect Git LFS to do if it can't download a file due to some server issue?
  * Halt current checkout/clone/pull command
  * Pointer file
  * Nothing  

Thanks for posting this feedback!
