### ISSUE TITLE
build scripts which use "ln -s" make Windows devs sad

### ISSUE THREAD

**Issue by shiftkey** [github/git-lfs#110]
This requires elevation to do on Windows :cry:, and I'm not familiar enough with how go is resolving dependencies to suggest a better option. I've hacked around it in the meantime.

**Comment by strich** [comment]
> I also didn't figure there'd be that many windows devs. There should be prebuilt binaries for users of course.
Just as an FYI you may be finding that the **majority** of your users will be Windows-based as this kind of project is highly applicable to GameDev.

**Comment by rubyist** [comment]
Good point, @strich.

#194 adds the ability to make the project `go get`-able, which has the side effect of making it `go build`-able. The reason we used a symlink in the build file before was because we had the project structured in a non-idomatic way for a go app. At this point we should be able to ditch the symlink and just set the GOPATH so that it uses the vendored go packages instead of ones that might be installed on the system.

**Comment by kofalt** [comment]
Dumb question - what does Windows git do when it checks out a repository with symlinks?

I recall Windows having concepts of a "hard" and "soft" link, and I could swear that you can get away with one of them as a non-Administrator role. But I could be wrong.

**Comment by technoweenie** [comment]
@strich: I was referring to contributors to the github/git-lfs Go project being on Windows.  I definitely agree about a majority of Git LFS users being on Windows :)

**Comment by technoweenie** [comment]
This was fixed awhile ago :)
