### ISSUE TITLE
git-lfs-upload should include information about the original filename

### ISSUE THREAD

**Issue by sschuberth** [github/git-lfs#1108]
Currently, the server has no information about the original file name once the LFS object has been uploaded. This has at least two drawbacks:

* When browsing the server, e.g. Artifactory, you have no clue about what the different LFS objects are. The original filename would give a hint here.

* When starting a new local repo that you want to add existing LFS objects to, you would have no idea what a proper filename for an exitsing LFS object would be.

If the `objects` array in the `POST` [command](https://github.com/github/git-lfs/blob/master/docs/api/http-v1-batch.md#post-objectsbatch) would have a `filename` entry, the server could optionally store that as meta-data along with the LFS object.

**Comment by javabrett** [comment]
Would that path be only the initial location of the blob? How should any subsequent copies or moves be handled?

**Comment by sschuberth** [comment]
Yes, I was just thinking to use the initial location of the blob. For simplicity, copies or moves should simply be ignored, i.e. the path should not be updated. It would not make much sense anyway, as different Git repositories could use the same LFS object under different file names. The `filename` entry should really be nothing more than a hint.

**Comment by sinbad** [comment]
I'm not in favour of this. Like git the lfs object store is simply a *content store*, derived only from the byte content. The same content can be referenced in multiple locations at different times, either because of moves or just because the same content is used in several locations. This is why git stores tree objects which point to content, and that works for git-lfs too, it's just that the object content is externalised. Git doesn't have pointers backward from content to tree objects and neither should we.

You can re-construct this information from the git commit objects using a command like `git log -G "oid sha256:9789e044f1dba123169dee7129838147a07d0917c0dd63cff9dd117485efe1fe" --name-status`.

**Comment by sschuberth** [comment]
> You can re-construct this information from the git commit objects using a command like...

Right, but only if you have access to the repo that originally uploaded the LFS objects.

I see your point about "Git doesn't have pointers backward from content to tree objects and neither should we", however. It's just that, compared to Git, due to the externalization it might be impossible to get back to what in Git would be the tree objects. Thus my proposal about the meta-data.

**Comment by sinbad** [comment]
I still think it's conceptually wrong and potentially misleading, for essentially a nicety. I don't like it but we can see what @technoweenie thinks.

**Comment by sschuberth** [comment]
Yeah, I'm fine with closing this if the consensus is that we do not want to be able to get back to the original filename in either this or another way.

**Comment by technoweenie** [comment]
I'm :-1: on this as an explicit part of the LFS API. However, figuring out where your files are used is important. I think this is more appropriate as some kind of troubleshooting LFS command that operates on your local repository.

Servers that host Git and LFS content can also get this by analyzing git pushes. Servers should do this to detect and potentially clean up old objects unreferenced by any git commit (due to a bad upload, branch deletion, or force push). This info that relies on the git repository can be trusted much more than an LFS API call that could receive partial or incorrect filename metadata.

**Comment by sschuberth** [comment]
> Servers that host Git and LFS content can also get this by analyzing git pushes.

Right, but I don't see that to be the usual use-case, at least not in commercial environments. Over there people are more likely to use e.g. Gerrit for Git and Artifactory for LFS hosting, so it's not feasible to detect old Git objects etc.

But I acknowledge including information about the original filename (only) is probably not the right thing to do. General usage tracking would be a better general idea, but I currently cannot think of how to implement it. So I'll withdraw my proposal for now by closing it.

**Comment by technoweenie** [comment]
Cool, thanks for opening it! My hope is that over time LFS servers will get better. The good ones will, at least :)

FWIW, Git LFS v1.2 will be sending some meta data with uploads and downloads (specifically, ref information): https://github.com/github/git-lfs/pull/969. It's possible this will work out really well, and we can look at sending more meta data like you proposed. My hunch is that instead we'll wind up with better guidelines on what a good LFS server _should_ do, and we'll be able to rip out the API meta data at some point.

This shouldn't necessarily exclude 3rd party tools like Gerrit or Artifactory. It doesn't seem crazy that they should have read access to the git repo. Or, maybe we can add more server endpoints that can be implemented on git hosts like GitHub, that a tool like Gerrit can use without needing to access the git repository directly.

**Comment by sinbad** [comment]
Yeah to me this sounds like if you don't want to have the git repo locally, maybe you can get it from an API on the git host (although this is less portable than having the git repo).

The reason I'm so against this particular bit of metadata is that unlike the ref information in #969 it's not naturally part of the resolution of this information. When you push you derive what to push from a ref (most of the time) so you naturally have that information already. Resolving the original tree-ish source of a content object though is both relatively expensive, because git just isn't designed to navigate it in that direction primarily, and the results are n-ary. If we say that we're going to provide that information, then we're locking ourself into a contract to provide information that's expensive and a bit awkward to retrieve, which will slow us down today and limit what we can do in future, for something that isn't really needed by most and could be derived another way by the few that do. 

For this reason I think we need to be careful about what we agree to in terms of supplying derived data as a matter of course, and only provide things which naturally fall out of the core model at basically zero cost. This one is pretty cut & dried in my view but in general I may refer back to this discussion in future when more are requested :)
