### ISSUE TITLE
add --skip-smudge option for cloning/pulling

### ISSUE THREAD

**Issue by Felk** [github/git-lfs#1137]
People who didn't install lfs with that option might still want to clone a repository without downloading all the large files. Possible usecases assuming the user does not want to temporarily reconfigure lfs for one clone:

- User does not need or want the large files (e.g. if their internet is slow)
- lfs runs on a different server which needs extra credentials the user doesn't have. But he should still be able to clone the repository

**Comment by sinbad** [comment]
The upcoming 1.2 release includes a `git lfs clone` command which allows people who would have used `--skip-smudge` and then pulled to clone more efficiently and easily.

For people who *never* want to get large files for a particular clone (rather than just do it more efficiently like `git lfs clone`), the best way is this:

`git -c filter.lfs.smudge=cat clone <url>`

or if using git version 2.8.0+, this is even faster:

`git -c filter.lfs.smudge= clone <url>`

Use the same `-c` option to any subsequent commands or define it in your repo's `git/config`. It's not possible for us to add `--skip-smudge` to `git clone` or `git pull` since they're core commands.
