### ISSUE TITLE
Unclear how GIT_SSH env var works

### ISSUE THREAD

**Issue by hbons** [github/git-lfs#1142]
With Git, when providing custom ssh commands with GIT_SSH, you always had to wrap the command in a shell script because Git would only allow a single argument to be passed. This lead to the introduction of [GIT_SSH_COMMAND](https://github.com/git/git/blob/master/Documentation/RelNotes/2.3.0.txt#L25) in version 2.3, which allowed arguments.

Which behaviour is correct when using GIT_SSH with git-lfs?

**Comment by technoweenie** [comment]
Hey @hbons, great question. Apparently our use of `GIT_SSH` was wrong: https://github.com/github/git-lfs/issues/1132. This will be fixed in Git LFS v1.2, out later this week, hopefully: https://github.com/github/git-lfs/pull/1134

This is a small fix, but I intend to look into `GIT_SSH` vs `GIT_SSH_COMMAND` in more detail after we ship v1.2. If you (or anyone that stumbles on this issue) wants something small to start contributing to LFS, let me know! Otherwise, I'm happy to answer questions or get feedback through issues too :)

**Comment by hbons** [comment]
Would love to contribute, but I don't know Go. :)

My suggestion would be to just implement GIT_SSH_COMMAND, and point GIT_SSH to the same logic. As GIT_SSH_COMMAND does everything GIT_SSH does there's not need for the latter anymore, but keep it around for backward compatibility.

**Comment by technoweenie** [comment]
Fair enough! Thanks for the feedback, it's on our roadmap: https://github.com/github/git-lfs/pull/1145
