### ISSUE TITLE
What is the easiest way to duplicate a local repo directory to another directory?

### ISSUE THREAD

**Issue by svermeulen** [github/git-lfs#1152]
Sorry if this is not an appropriate issue - I wasn't sure where to ask this.

Before I converted over my repo to git LFS, I would often copy and paste my repo directory so that I could work on multiple different problems at once, or compare different branches without having to jump between them, etc.  But with git LFS I'm finding this doesn't really work the same anymore.

After I copy and paste my repo directory, the first thing I try is `git status` which takes a really long time and eventually lists as modified what looks like every file that is tracked by git LFS.  At this point I can do a "git clean -xdf" and "git reset --hard" and most of the time this fixes it.  But I also sometimes find that some files will still remain marked as "modified", even after repeatedly running "git reset --hard".  So for these files I just delete them manually then run "git reset --hard" again which finally results in "git status" showing nothing which is what I want.  I should also mention that I'm working on windows 10.

So I'm able to eventually get it working, but I feel like I'm not understanding something important about how git LFS works.  I would have assumed that copying and pasting a local git repository would not require these extra steps, since I would have thought that each repo folder exists independently of all other repo folders.  And renaming a folder does not come with these issues.  Anyway, apologies for the length of this - mostly I'm just wondering if there an easier way to do this?

**Comment by technoweenie** [comment]
As of Git LFS v1.2, you can do this the normal Git way:

    $ git clone --reference path/to/old/repo path/to/old/repo new-repo-dir

Also, it sounds like your repository isn't fully converted to LFS, so that may be causing problems. The `git lfs track` command only changes `.gitattributes`, which only takes effect as files are added or changed from that point on. Any existing files are still plain git blobs, and running `git status` on a copied repository directory probably triggers Git's clean filter, causing LFS to change it to a pointer, hence the modified files.

Incidentally, `git lfs track` on v1.2 helps this too, by bumping the timestamp on all matching files when you run it, causing all of the _current_ LFS objects to get updated right there.

Hope that helps! Let me know if you have other questions.

**Comment by svermeulen** [comment]
Oh awesome, I didn't notice that 1.2 was out.  The new `git lfs clone` command sounds like it will also be a huge help for us

I tried your suggestion of `git clone --reference` and that did the trick nicely.  Thanks!

Keep up the good work!
