### ISSUE TITLE
Integration of git lfs with artifactory

### ISSUE THREAD

**Issue by rmpaul** [github/git-lfs#1187]
How do we pass credentials for artifactory when pushing the files using `git lfs push origin`

**Comment by technoweenie** [comment]
Git should automatically ask you. If you have [git credential caching enabled](https://help.github.com/articles/caching-your-github-password-in-git/), then Git will remember it after the first successful push.

**Comment by davidwoon** [comment]
Looking through all the previous 'closed' issues and this, I was able to follow and get my git-lfs artifactory repo setup. git credential caching only works locally. Prompts for 1st time username/password entry on a CI/CD setup, in my case Jenkins is a blocker. Are there any examples, solutions to automated git-lfs repo engagements?

**Comment by technoweenie** [comment]
Closing this, until there are more details on a potential artifactory issue.

Jenkins issues should be discussed outside of an artifactory issue. It's a weird case because the Jenkins Git plugin doesn't use the regular git commands. It'll have to be modified to call `git lfs pull` manually. Also, there's some really basic support for "git alternates" as seen in https://github.com/github/git-lfs/pull/1007. This may be useful if you want each jenkins server to hold all the LFS objects in one directory, regardless of which jenkins sub directory is cloning repositories for tests.
