### ISSUE TITLE
Smudge filter error issuing pull from peer repository

### ISSUE THREAD

**Issue by hhedeshiangogo** [github/git-lfs#1227]
**Description**: Unable to 'git pull' from peer repository if the peer contains changes to files managed by lfs and those changes have not been pushed to github.

**Steps to reproduce:**
1. Suppose you have some repo on github, we'll call it 'M'.
2. Person 'A' clones M. `git clone ...`
3. Person 'B' clones M. `git clone ...`
4. Person 'A' makes a change in a local branch.
`git checkout -b mybranch`
`git add ..`
`git commit ...`
5. Person 'B' tries to pull that branch from person 'A' into their repo. 
`git checkout -b person_a_branch`
`git remote add personA user@personA:/path/to/repo`
`git pull personA mybranch`

**Desired outcome:**
Git LFS should pull the object from the peer repository instead of the lfs cache on github.

This works fine if there are no objects managed by LFS changed in person 'A's branch (e.g.. regular text files). This is caused by LFS looking for the changed file on github but does not exist since 'A' never pushed it to github.

**Error message:**
Use `git lfs logs last` to view the log.
error: external filter git-lfs smudge %f failed 2
error: external filter git-lfs smudge %f failed
fatal: somefile.tar.gz: smudge filter lfs failed
could not detach HEAD

**Logs:**
_(I removed proprietary stuff from these logs)_
[foor@bar bam$] git lfs logs last
git-lfs/1.2.0 (GitHub; linux amd64; go 1.5.3; git 386c5d8)
git version 2.8.2

$ git-lfs smudge somefile.tar.gz
Error downloading object: somefile.tar.gz
074d48dfc28b5267566a0a175bceae11cc1cf86097ebe46444013ca19b2e0636)

Object not found on the server.
goroutine 1 [running]:
github.com/github/git-lfs/lfs.Stack(0x0, 0x0, 0x0)
        /tmp/docker_run/git-lfs/rpm/BUILD/git-lfs-1.2.0/src/github.com/github/git-lfs/lfs/errors.go:566 +0x80
github.com/github/git-lfs/commands.logPanicToWriter(0x7fc6ee61f358, 0xc820150020, 0x7fc6ec597408, 0xc820148330)
        /tmp/docker_run/git-lfs/rpm/BUILD/git-lfs-1.2.0/src/github.com/github/git-lfs/commands/commands.go:195 +0xf7f
github.com/github/git-lfs/commands.logPanic(0x7fc6ec597408, 0xc820148330, 0x0, 0x0)
        /tmp/docker_run/git-lfs/rpm/BUILD/git-lfs-1.2.0/src/github.com/github/git-lfs/commands/commands.go:159 +0x421
github.com/github/git-lfs/commands.handlePanic(0x7fc6ec597408, 0xc820148330, 0x0, 0x0)
        /tmp/docker_run/git-lfs/rpm/BUILD/git-lfs-1.2.0/src/github.com/github/git-lfs/commands/commands.go:134 +0x4e
github.com/github/git-lfs/commands.LoggedError(0x7fc6ec597408, 0xc820148330, 0x98a220, 0x21, 0xc820131c98, 0x2, 0x2)
        /tmp/docker_run/git-lfs/rpm/BUILD/git-lfs-1.2.0/src/github.com/github/git-lfs/commands/commands.go:84 +0x82
github.com/github/git-lfs/commands.smudgeCommand(0xd732e0, 0xc820011d00, 0x1, 0x1)
        /tmp/docker_run/git-lfs/rpm/BUILD/git-lfs-1.2.0/src/github.com/github/git-lfs/commands/command_smudge.go:79 +0xdca
github.com/github/git-lfs/vendor/_nuts/github.com/spf13/cobra.(*Command).execute(0xd732e0, 0xc820011c50, 0x1, 0x1, 0x0, 0x0)
        /tmp/docker_run/git-lfs/rpm/BUILD/git-lfs-1.2.0/src/github.com/github/git-lfs/vendor/_nuts/github.com/spf13/cobra/command.go:477 +0x403
github.com/github/git-lfs/vendor/_nuts/github.com/spf13/cobra.(*Command).Execute(0xd74320, 0x0, 0x0)
        /tmp/docker_run/git-lfs/rpm/BUILD/git-lfs-1.2.0/src/github.com/github/git-lfs/vendor/_nuts/github.com/spf13/cobra/command.go:551 +0x46a
github.com/github/git-lfs/commands.Run()
        /tmp/docker_run/git-lfs/rpm/BUILD/git-lfs-1.2.0/src/github.com/github/git-lfs/commands/commands.go:99 +0x23
main.main()
        /tmp/docker_run/git-lfs/rpm/BUILD/git-lfs-1.2.0/git-lfs.go:34 +0x12e

**Comment by hhedeshiangogo** [comment]
Possibly related to "#1116"

**Comment by technoweenie** [comment]
Ah, so there are two weaknesses with LFS here. First, LFS uses git's internal "smudge" filter to download files automatically during a `git pull`. Basically, it's calling `git lfs smudge ...` for every file as it's being updated in the git working directory. Due to the way git works, the context of which remote was pulled from is lost. One option is to turn off the smudge filter ([via `git lfs install`](https://github.com/github/git-lfs/blob/355eedc706992238feed8adf4f1e795f5c383c50/docs/man/git-lfs-install.1.ronn#L27-L30)). This means you'll be forced to use `git lfs pull` to download any needed objects. But, you can specify custom remotes like `git lfs pull personA`. Since git doesn't tell its smudge hooks which remote was just used, it assumes `origin`. 

The second is that Git LFS currently needs to talk to a server. It's possible that we will add a pure ssh api for LFS, or even embed a simple server in Git LFS that you can spin up for your use case. But, we're trying to focus on the core LFS user experience before branching out into multiple APIs.

Also, not quite related to #1116. The "Object not found on the server." error is because you're trying to download an object that your coworker added, but hasn't pushed to github yet.

**Comment by hhedeshiangogo** [comment]
Got it, thanks for taking a look. I just ended up using rsync to pull the whole tree since that seemed like the path of least resistance.

"git doesn't tell its smudge hooks which remote was just used" Just curious, are there plans to try to change that behavior upstream? Or is it even feasible architecturally?

I'm not sure about the "simple Git LFS" server. Perhaps that seems overkill for simple peer-to-peer exchanges? I think the ideal solution would be to make LFS transparent to the usual git distributed work flow.

Thanks a bunch.

**Comment by technoweenie** [comment]
> "git doesn't tell its smudge hooks which remote was just used" Just curious, are there plans to try to change that behavior upstream? Or is it even feasible architecturally?

I'm not sure it's possible, since smudge hooks are also called when changing branches with `git checkout {branch}`, which has no interaction with a remote. I think your best bet would be to turn off smudge, and run `git lfs pull {remote}` manually, with the correct remote.

One really hacky solution would be supporting something like: `LFS_REMOTE={remote} git checkout {branch}`, and looking for the env var in `git lfs smudge`. It's not at all intuitive, and doesn't take advantage of the concurrent object downloading that `git lfs pull` uses.
