### ISSUE TITLE
Command-line switches don't override .lfsconfig file

### ISSUE THREAD

**Issue by dipnlik** [github/git-lfs#1249]
Currently I have a LFS-enabled repo with the following `.lfsconfig` file:

```
[lfs]
	fetchexclude = spec/fixtures/vcr_cassettes/**/*.yml
```

The expected behavior is that when anyone clones the repo, by default none of the big LFS-enabled .yml files are downloaded.  I cloned the repo and this worked as expected.

Then I ran `git lfs pull -I spec/fixtures/vcr_cassettes/gbcoffice`, expecting the command line options to override the config file and actually download the files I requested, but it did not.

Also tried `git lfs pull -I spec/fixtures/vcr_cassettes/gbcoffice -X ""`, same behavior.

If I move/remove the config file, the commands work as expected, but moving/removing the file should not be needed when I'm being explicit about my intentions via command-line switches.

If you need any other information, feel free to ask.

**Comment by shoelzer** [comment]
I came here to report this same issue because I want to use LFS the same way. Glad to see that @dipnlik reported it already.

Are there any other workarounds besides temporarily changing `.lfsconfig`?

**Comment by ttaylorr** [comment]
Hi, thanks for opening this. @dipnlik is `spec/fixtures/vcr_cassettes/gbcoffice` a directory, or a file?

**Comment by dipnlik** [comment]
`spec/fixtures/vcr_cassettes/gbcoffice` is a directory.  It has 3 files: `categories.yml`, `subcategories.yml` and `offers.yml`.

```
# .gitattributes
spec/fixtures/vcr_cassettes/**/*.yml filter=lfs diff=lfs merge=lfs -text
```

```
# git lfs env
git-lfs/1.2.0 (GitHub; darwin amd64; go 1.6.1)
git version 2.7.4 (Apple Git-66)

Endpoint=https://github.com/mercadoeletronico/agents-lfs.git/info/lfs (auth=none)
  SSH=git@github.com:mercadoeletronico/agents-lfs.git
LocalWorkingDir=/Users/dip/Dropbox/Developer/mercadoeletronico/agents-lfs
LocalGitDir=/Users/dip/Dropbox/Developer/mercadoeletronico/agents-lfs/.git
LocalGitStorageDir=/Users/dip/Dropbox/Developer/mercadoeletronico/agents-lfs/.git
LocalMediaDir=/Users/dip/Dropbox/Developer/mercadoeletronico/agents-lfs/.git/lfs/objects
LocalReferenceDir=
TempDir=/Users/dip/Dropbox/Developer/mercadoeletronico/agents-lfs/.git/lfs/tmp
ConcurrentTransfers=3
BatchTransfer=true
GIT_PS1_SHOWDIRTYSTATE=1
GIT_PS1_SHOWSTASHSTATE=1
git config filter.lfs.smudge = "git-lfs smudge -- %f"
git config filter.lfs.clean = "git-lfs clean -- %f"
```

If you need anything else, just ask.  Thanks in advance for looking at this issue.

**Comment by ttaylorr** [comment]
Aha! I added support for directory-based include/exclude filters in v1.2.1. Could you install the latest version of LFS and try again?

**Comment by dipnlik** [comment]
@ttaylorr updated my LFS installation via Homebrew to `git-lfs/1.3.0 (GitHub; darwin amd64; go 1.6.3)`, and the issue still occurs.

**Comment by ttaylorr** [comment]
Ah. @technoweenie provided a very helpful explanation to me of what's going on here, which I'm going to share here.

The exclude filter that is specified in your `.lfsconfig` file is being negated by the `-I` flag, which _should_ allow LFS to include it in fetches/clones/pulls. However, it is still comparing against the exclude filter found in `.lfsconfig` because even when `-X` isn't given (or is given as `-X ""`), LFS sees an empty string internally, and signals itself to fallback to the ones found in the config (see [here](https://github.com/github/git-lfs/blob/701cc0c56c298ba29a5aab2ec88c19150fd84c42/tools/filetools.go#L108-L110)).

After it fallsback, both the `include` _and_ the `exclude` filters are set to the same path, and are thus [ignored](https://github.com/github/git-lfs/blob/b414b58bc3b6d34dfe87c01c9c481605d6fc8ca7/lfs/util.go#L121-L128) by the filter checking mechanism, thereby excluding your files.

The most reasonable fix I think would be to check if `*string == nil` instead of `len(string) == 0`, but some sort of special token like `"<ignore>"` would work as well. 😄 

Kudos to @technoweenie! ⚡
