### ISSUE TITLE
Error pushing despite correct setup

### ISSUE THREAD

**Issue by BenjaminSchumann** [github/git-lfs#1275]
Hi,

not sure if this is the correct way to ask for help. If not, delete this. I searched for similar issues...

Essentially, I believe I set up lfs correct but it still refuses to push my 120MB .bak file.

Here is my gitattributes: 
![unnamed](https://cloud.githubusercontent.com/assets/16608112/15746406/bbbfdbda-28d6-11e6-934a-ebe9604017be.png)

Our Git account should have enough space for the lfs file:
![unnamed 1](https://cloud.githubusercontent.com/assets/16608112/15746442/d2206a84-28d6-11e6-89ed-a7f09811967b.png)

However, when I push the repo, it actually looks like it uploads the 120 MB file (takes ~3 mins). However, once finishing the upload, it displays the same error I would get _without_ installing lfs in the first place, see below. Also note that `git lfs ls-files` actually lists the file.
![capture](https://cloud.githubusercontent.com/assets/16608112/15746576/710f3fb2-28d7-11e6-8c15-60c41d5222f3.PNG)

Am I missing something here?
thx a lot in advance for any pointers

**Comment by technoweenie** [comment]
The `.gitattributes` file needs to be set when files are added to the repository. It doesn't take effect for files that were already added. Since that large file hasn't been pushed, this guide can help you roll the history back, so you can re-add it with Git LFS:  https://help.github.com/articles/removing-files-from-a-repository-s-history/
