### ISSUE TITLE
Git Push Tags command ignores lfs

### ISSUE THREAD

**Issue by LukeDurrant** [github/git-lfs#1413]
Unable to push git tags with lfs I wasn't adding this file its already in the git
when I do 
`git lfs ls-files`
50a180d712 * Pods/GoogleMaps/Frameworks/GoogleMaps.framework/Versions/A/GoogleMaps

See error below
```
[06:58:58]: Exit status of command 'git push origin beta:beta --tags' was 1 instead of 0.
remote: error: GH001: Large files detected. You may want to try Git Large File Storage - https://git-lfs.github.com.        
remote: error: Trace:        
remote: error: See http://git.io/iEPt8g for more information.        
remote: error: File Pods/GoogleMaps/Frameworks/GoogleMaps.framework/Versions/A/GoogleMaps is 123.08 MB; this exceeds GitHub's file size limit of 100.00 MB        
 ! [remote rejected] beta -> beta (pre-receive hook declined)
 ! [remote rejected] v601_74_beta -> v601_74_beta (pre-receive hook declined)
error: failed to push some refs to '****.git
```

**Comment by ttaylorr** [comment]
Hey, @LukeDurrant -- thanks for opening this issue. Off the top of my head, I'm not sure if LFS can hook into a `git push <remote> --tags`, but this workaround may get you there in the meantime:

```
$ git lfs push <remote>
$ git push <remote> <branch> --tags
```

**Comment by sinbad** [comment]
The underlying problem appears to be that `Pods/GoogleMaps/Frameworks/GoogleMaps.framework/Versions/A/GoogleMaps` is a large file but hasn't been tracked using `git lfs track`, it's just been committed directly to Git instead. GitHub has a pre-receive hook which throws that error if you try to push files >100MB embedded in Git, rather than tracked in LFS. So this isn't actually an LFS issue.

If you want to stop this error you'll have to rewrite your local history to before when you added `Pods/GoogleMaps/Frameworks/GoogleMaps.framework/Versions/A/GoogleMaps`, and use `git lfs track <foo>` (with an appropriate path matcher, depending on whether it's just this file or all files in the dir etc), then `git add` and `git commit` the file again before pushing.

**Comment by sinbad** [comment]
> you'll have to rewrite your local history to before when you added 

To be more specific, one way to do this if you committed that file first in commit (say) `a1b2c3`, you could do `git reset --mixed a1b2c3^`. This would discard any commits from `a1b2c3` onwards but keep your working copy the same. You could then do `git lfs track ...`, `git add ...`, `git commit` and then push. You'd have to be happy to discard those commits of course.
