### ISSUE TITLE
`git lfs clone` errors with `unexpected EOF`

### ISSUE THREAD

**Issue by larsxschneider** [github/git-lfs#1433]
I have a repository with a number of submodules that contain Git LFS files.

If I run `git lfs clone http://myrepo` I get this:
```
...
Submodule path '<<redacted>>': checked out '2ce6e6b1f21926163ffa5df
4d561c46f54ab88c0'
Submodule path '<<redacted>>': checked out '6f432dbb51f33dff47a57f93
ca4182d1d6a2ebe4'
Git LFS: (9 of 9 files) 6.62 MB / 6.62 MB
Git LFS: (27 of 27 files) 10.80 MB / 10.82 MB
Git LFS: (3 of 3 files) 87.81 KB / 90.48 KB
Git LFS: (77 of 77 files) 4.49 MB / 4.54 MB
Git LFS: (2993 of 2999 files) 2.30 GB / 2.34 GB
cannot write data to tempfile "D:\\git\\<<redacted>>\\.git\\modules\\<<redacted>>
hicleLibs\\lfs\\objects\\incomplete\\46d7472c30b5b53787a9272a3fca6afc2e3464fef18
b9e743081fbe6da59a5b6.tmp": unexpected EOF
```

The error seems to happen here:
https://github.com/github/git-lfs/blob/42eec79523f654f904faabc7d4722f65d3348960/transfer/basic_download.go#L204-L206

System that was used when the error was observed:
git version 2.9.2.windows.1
git-lfs/1.3.1 (GitHub; windows amd64; go 1.6.3; git 9c9dffb)

I wasn't able to reproduce this error on my Windows and Mac boxes, yet. Any idea what this might be and how to debug this further?

AFAIK this should not be a "disk full" problem but I will double check this.

**Comment by ttaylorr** [comment]
Hmm... this looks like one of these may be the problem? https://github.com/github/git-lfs/blob/42eec79523f654f904faabc7d4722f65d3348960/transfer/basic_download.go#L180-L186

**Comment by sinbad** [comment]
Looks like it's during the actual file write rather than when building the hasher, so https://github.com/github/git-lfs/blob/master/transfer/basic_download.go#L206. 

I think "Unexpected EOF" is more likely to come from the read end of the copy rather than the write end, the error would (I believe) be a separate disk full message or write error. The copy knows the expected length so any interrupted transfer would result in that kind of message. I have built on Windows and run some submodule tests, but never with that level of data since I don't have submodule examples that big.

**Comment by larsxschneider** [comment]
The `unexpected EOF` error is defined [here](https://github.com/golang/go/blob/master/src/io/io.go#L40-L42). But only `ReadAtLeast` and `ReadFull` [can trigger this error](https://github.com/golang/go/blob/master/src/io/io.go#L294-L326). We don't use these functions I think...

**Comment by ttaylorr** [comment]
> Looks like it's during the actual file write rather than when building the hasher

I was suggesting that the hasher that gets built and passed into the function that you pointed out may be the culprit.
