### ISSUE TITLE
Option to 'git lfs clone -I/-E' not to fetch files at all?

### ISSUE THREAD

**Issue by woopla** [github/git-lfs#1484]
Hello,

I'd like for `git lfs clone -I` to avoid even downloading the `stub` files that contain the LFS metadata. IOW, I would like to have the same behaviour as 'git read-tree', which only creates the files of interest in the directory tree.

Thanks,

Clément

**Comment by ttaylorr** [comment]
@sinbad @technoweenie thoughts?

**Comment by sinbad** [comment]
The trouble with not writing the pointers/stubs to the disk is that `git status` will report those files missing if they're not there at all, which is very likely to cause issues.

In any case, you'll never avoid *downloading* those stubs, because they're embedded in the git commit data which cannot be selectively cloned by path. So you'd have them locally anyway all we could do would be avoid writing the pointers to disk which would cause the problems above.

So I don't think this is practical, sorry.

**Comment by ttaylorr** [comment]
I agree. Closing this out, sorry.

**Comment by woopla** [comment]
Thanks for the info @sinbad . I'll stick to sparse checkouts and `git read-tree -mu`, since it works :smiley_cat:
