### ISSUE TITLE
Git lfs pull doesn't download anything or produce an ouput

### ISSUE THREAD

**Issue by theNewFlesh** [github/git-lfs#1511]
I am unable to get `git lfs pull` to do anything (ie no output).

.lfconfig file:
```
[filter "lfs"]
        clean = git-lfs clean %f
        smudge = git-lfs smudge %f
        required = true
[lfs]
	url = "http://localhost:8080"
	batch = false
	access = basic
```
I am running [git-lfs-s3](https://github.com/meltingice/git-lfs-s3) as a local server which connects to a remote S3 bucket.

git lfs fetch also doesn't do anything unless I run git fetch --all first and run it with --all or repo + commit-hash.

git version 2.7.4 (Apple Git-66)
git-lfs/1.4.1 (GitHub; darwin amd64; go 1.7; git 2070e4c)

**Comment by technoweenie** [comment]
What does `GIT_TRACE=1 git lfs pull` show? It should print out the commit shas that LFS is scanning for Git LFS objects.  By default, Git LFS will only download what it needs to satisfy your working directory.  The `--all` flag tells git lfs to scan the entire repository history for every large object, which is not something you'd want unless you're transferring between LFS servers.

**Comment by theNewFlesh** [comment]
Here is my output:
```
GIT_TRACE=1 git lfs pull
14:14:03.264367 git.c:561               trace: exec: 'git-lfs' 'pull'
14:14:03.264858 run-command.c:334       trace: run_command: 'git-lfs' 'pull'
trace git-lfs: run_command: 'git' version
trace git-lfs: run_command: 'git' rev-parse HEAD --symbolic-full-name HEAD
trace git-lfs: run_command: 'git' config branch.master.remote
trace git-lfs: run_command: 'git' config -l -f /Users/alex/Documents/projects/test/b/.lfsconfig
trace git-lfs: run_command: 'git' config -l
trace git-lfs: run_command: 'git' rev-parse HEAD --symbolic-full-name HEAD
trace git-lfs: run_command: git ls-tree -r -l -z --full-tree 1b7166548f128c2dffa9d35865cc0ac25c3d1c89
trace git-lfs: run_command: git cat-file --batch
trace git-lfs: run_command: 'git' rev-parse HEAD --symbolic-full-name HEAD
trace git-lfs: tq: running as individual queue
trace git-lfs: run_command: git ls-tree -r -l -z --full-tree 1b7166548f128c2dffa9d35865cc0ac25c3d1c89
trace git-lfs: run_command: git cat-file --batch
```

**Comment by theNewFlesh** [comment]
My goal is to perform pulls with include/exclude conditions.  However, I need to utilize git/git lfs to do that is what I would like to know.

**Comment by technoweenie** [comment]
Git LFS is scanning `1b7166548f128c2dffa9d35865cc0ac25c3d1c89` for LFS objects, and not finding any that aren't already in `.git/lfs/objects`. You can also run `git lfs ls-files` to see what LFS objects Git LFS is finding in the repo.

**Comment by theNewFlesh** [comment]
git lfs ls-files doesn't produce any output.

I have an initial commit repo with .gitattributes and .lfsconfig only.  And I am trying to add in proj/speca001/some-file.obj and proj/speca001/some-file.yml from a repo 4 commits ahead.

.gitattributes:
```
*.obj filter=lfs diff=lfs merge=lfs -text
```

**Comment by ttaylorr** [comment]
👋  @theNewFlesh. I'm Taylor, I also work on LFS.

`git lfs ls-files` will only tell you about objects that you have already committed (not just staged). Due to a limitation imposed upon us by `.gitattributes`, you have to commit objects that you want to store with LFS _after_ adding selectors for those types of files to `.gitattributes`.

For instance, if you did the following:

0. Commit `a.dat`, hoping that it will be tracked by LFS
0. Run `git lfs track *.dat`, and the commit `.gitattributes`

The `a.dat` file will not be tracked by Git LFS unless you reordered the commits from steps 1 and 2.

That all being said, have you _committed_ your `.gitattributes` file with the `*.obj` selector (by running `git lfs track *.obj`) before staging and committing the `.obj` files themselves?

**Comment by theNewFlesh** [comment]
Yes, my initial was just that and only that.

**Comment by theNewFlesh** [comment]
It's a private repo, I added you both.  See for yourselves.

**Comment by ttaylorr** [comment]
@theNewFlesh thanks for adding me! That's super helpful.

I'm seeing that commits 972a5ef..aa15bb8 all have LFS objects in them. To verify, open up one of those commits on the website, and all of the *.obj files will display the message `Git LFS file not shown`.

**Comment by theNewFlesh** [comment]
All my objs are proper pointer files. For example:
```
version https://git-lfs.github.com/spec/v1
oid sha256:eb5329b439fa8264463afd4d122d7ca045e7a2678e014fc061f2a2a4009a755e
size 13270551
```

**Comment by ttaylorr** [comment]
If that is the case and you've done a `git lfs push`, then a `git lfs push` or `pull` will produce no output, meaning that you're in sync. We should probably update this with git's `Already up to date` message, which I will do now.

For now, I'm going to close this issue as everything is technically 👌

**Comment by theNewFlesh** [comment]
git lfs push origin master produces no output.
However, my goal is to perform pulls with include/exclude conditions and that isn't working.  So, can you tell me how I might go about doing this?

**Comment by ttaylorr** [comment]
Sorry for closing your issue! I misunderstood what you were looking for.

You can use the `-I` and `-X` flags on `pull` to specify a glob you wish to include or exclude, respectively. More information on these flags can be found [in our documentation](https://github.com/github/git-lfs/blob/411305b5b99ea17f26d29a047fa82b84b72d02a8/docs/man/git-lfs-pull.1.ronn#L18-L35).

Since you are already up to date with the remote, however, there are no objects to push/pull in the first place, so no output is generated. If you want to simulate this sort of behavior, you can dump all of the objects you have stored locally by removing the `.git/lfs/objects/` directory, and trying the push or pull again with the desired include and exclude filters applied.

**Comment by theNewFlesh** [comment]
Those filters don't work for fetch or pull.  The trouble if that the repo thinks it is up to date when it isn't.  So I run git fetch --all and then git status will say I am # commits behind.  However, git lfs status is the same.  Git lfs fetch --all works, as does git lfs fetch repo commit-hash, but I want to exclude certain files/directories and they don't.

**Comment by theNewFlesh** [comment]
To be clear, my process has been to copy my repo (A) into a new directory called "B".
Then, in A, I add, commit and push some new LFS and non-LFS files using only git.  The files show up in S3.
This produces a version disparity between A and B.
I then wish to perform a pull on B, such that I pull certain LFS files but not others.

At this point (call it T0):
Running `git lfs pull` does nothing.
Running `git lfs fetch` does nothing.

Running `git fetch --all` changes my git status from up to date to # commits behind (call this T1).
At T1:
`git lfs fetch --all` will fetch all my lfs objects.
`git lfs fetch -I or -X` does nothing.
`git lfs pull` does nothing.
`git pull` fetchs all my lfs objects and puts them in my working directory.

**Comment by technoweenie** [comment]
The git lfs fetch and pull commands are based on your git HEAD. They don't run `git pull` or anything for you. Notice how nothing happens until you run `git pull` at T1:

> git lfs fetch --all will fetch all my lfs objects.
git lfs fetch -I or -X does nothing.
git lfs pull does nothing.
git pull fetchs all my lfs objects and puts them in my working directory.

It sounds like you want finer control over what LFS objects are pulled. Running `git pull` will fetch the latest git objects and check them out to your working directory. This runs the git smudge filter, which downloads Git LFS objects for you automatically. Since you're not running the smudge filter directly, the only way that you can apply include or exclude filters is by setting it in your git config:

> In gitconfig, set lfs.fetchinclude and lfs.fetchexclude to comma-separated lists
of paths to include/exclude in the fetch (wildcard matching as per gitignore).
Only paths which are matched by fetchinclude and not matched by fetchexclude
will have objects fetched for them.

It sounds like you want more fine grained control over this process though. You can run `git lfs install --skip-smudge` to disable the git smudge filter, requiring you to run `git lfs pull` every time your working directory changes. This adds an extra command to your workflow, but now you can apply `-I` or `-X` on a per-command basis.

```bash
$ git lfs install --skip-smudge
$ git pull
$ git lfs pull -I "*/*/proj_test"
```

**Comment by theNewFlesh** [comment]
That works.

**Comment by carlosquijano** [comment]
@technoweenie Useful information.

**Comment by HerveNivon** [comment]
That works so well 👌🏻
