### ISSUE TITLE
Fedora 21 OS

### ISSUE THREAD

**Issue by Seymourthings** [github/git-lfs#1525]
Hey, I'm using a virtual Fedora 21 machine for a homework assignment. I simply want to install git-lfs, and I've followed the instructions listed in the guide. However, after downloading the rpm from packagecloud and then attempting "sudo yum install git-lfs", there is no package found. But the installation seems to be fine, no echo messages complaining about the OS. Is Fedora 21 supported by git-lfs? And if not is there a workaround to getting this on my machine.?

**Comment by technoweenie** [comment]
Hi @Seymourthings, we don't currently push RPMs for Fedora 21 since it was [end of lifed at the end of 2015](https://en.wikipedia.org/wiki/Fedora_(operating_system)#cite_note-36). You can download a precompiled Linux from [the release page](https://github.com/github/git-lfs/releases), or run `go get github.com/github/git-lfs` if you have Go installed and want to compile it.
