### ISSUE TITLE
tracking of files anchored at the root of the repository fails on Windows

### ISSUE THREAD

**Issue by larsxschneider** [github/git-lfs#1531]
### Setup

```
git-lfs/1.4.1 (GitHub; windows amd64; go 1.7; git 2070e4c)
git version 2.9.2.windows.1 
Win 7 & Win 8.1
```

### Steps to reproduce

```bash
MINGW64 ~/my-repo (master)
$ echo "test" > test1.dat

MINGW64 ~/my-repo (master)
$ git lfs track /test1.dat
Error getting git tracked files

Errors logged to ....
Use `git lfs logs last` to view the log.
```

Tracking of files anchored at the root of the repository fails on Windows in Git Bash.

### Log

```
git-lfs/1.4.1 (GitHub; windows amd64; go 1.7; git 2070e4c)
git version 2.9.2.windows.1

$ git-lfs track C:/path/to/my/Git/test1.dat
Error getting git tracked files

exit status 128
```

**Comment by technoweenie** [comment]
Thanks for the report. Added to a v1.5.0 milestone. If @ttaylorr or someone else can submit a patch, I can see getting this into a v1.4.x release, but I personally don't have the time now.

**Comment by ttaylorr** [comment]
Thanks for the ping! I can take a look at this after I finish some work I'm doing on the transferqueue.

**Comment by ttaylorr** [comment]
Sorry for the late response! I just finished digging into this, here's what I found.

When you type `/a.dat` at the Windows shell, it turns that into `C:/Program Files/Git/a.dat`. This is usually outside of the Git repository (unless for some reason you're working in `C:/Program Files/Git`) so running `git ls-files` fails.

I don't think it's worth trying to change or guess the path that Windows is prepending, since this will break the expectations of Windows scripts. I do think, however, that we should improve the error message we're getting from `git lfs track` to include the error that we failed with when running the `ls-files` command.

Does this sound like a good approach?

**Comment by larsxschneider** [comment]
Hm... on Linux/OSX `/something` refers to something directly at the root of the file system. However, Git interprets that as "something at the root of the Git repository". I believe that is similar to what you mean with "break the expectations of Windows scripts", right?

When is `/a.dat` turned into `C:/Program Files/Git/a.dat`? I assume you see the latter as parameter in Go? What if we put parenthesis around the parameter (`git lfs track "/a.dat"`)?

**Comment by ttaylorr** [comment]
The conversion happens at the shell, before it is sent to LFS as an argument. Quoted strings have the same behavior. Should we maybe be responding to `\` instead? My preference would be to leave this behavior unchanged, and just improve the output.

**Comment by larsxschneider** [comment]
You mean a Windows user would write `git lfs track "\something"`?

In what environment did you observe the conversions? In `cmd.exe`, in `git-bash.exe`, or both?

**Comment by ttaylorr** [comment]
The conversion occurs in `git-bash.exe` only. `cmd.exe` works correctly with Git LFS, given a leading `/`.
