### ISSUE TITLE
Does git-lfs support ProxyCommand?

### ISSUE THREAD

**Issue by bitinn** [github/git-lfs#1624]
I setup `~/.ssh/config` like following:

```
Host          github.com
Port          22
User          git
HostName      github.com
IdentityFile  ~/.ssh/id_rsa.key
ProxyCommand  nc -x localhost:9002 %h %p
```

My proxy tool comes with a debug console, and while I do see `nc` making connections, I don't see much network traffic during a `git push`. Since git-lfs also goes through SSH, I am wondering if it obeys `ProxyCommand` or not?

**Comment by sinbad** [comment]
git-lfs only uses ssh to establish an authentication token which it can then use over HTTPS for the main bulk of the actual work, including API calls and uploads / downloads. So when push, there will only be a single ssh call at the start to retrieve this token using ssh, then the rest will be HTTPS traffic.

Because git-lfs uses your ssh client then it will respect any settings you've configured for it, including `ProxyCommand`.

**Comment by bitinn** [comment]
@sinbad Thx, it also mean I need to configure proxy setting manually right? Just setting system proxy (on OSX) is not enough.

**Comment by sinbad** [comment]
For HTTPS proxy? Yes, you'll need to do this: http://stackoverflow.com/questions/128035/how-do-i-pull-from-a-git-repository-through-an-http-proxy
