### ISSUE TITLE
storing entire file on windows?

### ISSUE THREAD

**Issue by javoire** [github/git-lfs#208]
Hey!

Either I've completely missed something or I can't get it to work the way it should.

I am tracking `*.bmp`
```
C:\test>git lfs track
Listing tracked paths
    *.bmp (.gitattributes)
```

And I've added and commited a bmp file.
```
C:\test>git add image.bmp

C:\test>git lfs status
On branch master

Git LFS objects to be committed:

        image.bmp (12.0 MB)

Git LFS objects not staged for commit:



C:\test>git commit -m "lfs test"
[master 4cf8bbc] lfs test
 1 file changed, 3 insertions(+)
 create mode 100644 image.bmp
```

It seems to be tracked
```
C:\test>git lfs ls-files
image.bmp
```

Now expect git-lfs to only store metadata of this file:
```
13M     ./image.bmp
```
and not the entire file:
```
13M     ./.git/lfs/objects/82/aa/82aaaebaf49f63cb82b4356136365943eea681f601bea4aa6d2caa7087ffe2be
```

Is this behaviour expected? I also did a test with modifying the file, and I ended up with two 13M objects.

Cheers!

**Comment by technoweenie** [comment]
Yes, that's expected.  You should see the text pointer if you run `$ git show 4cf8bbc`.

Git LFS does keep the entire file in the working directory AND the `.git/lfs/objects` directory.  There's no automatic cleaning process for the `.git/lfs/objects` directory, so it will continue to grow unbounded.  But, this is something we're discussing.

Also, once you've pushed all of the large objects to your Git LFS remote, you can wipe that `.git/lfs/objects` directory.  It acts as a cache, so future Git checkouts will re-download them from the server as needed.

> I also did a test with modifying the file, and I ended up with two 13M objects.

Do you have two separate commits with different versions of the file?  If so, Git LFS will upload both files on a `git push` since they're each referenced by a commit.

**Comment by javoire** [comment]
I see, so I had just misunderstood the concept, but I now see how this makes total sense. Thank you for clearing it up :)

Another unrelated thing though, is when I run
```
C:\test>git lfs clean
```
Or smudge, it just stays for several minutes with no output (haven't seen it ever complete). Is it supposed to take long for my 13M repo? I can add though that I have _not_ pushed anything anywhere, maybe it expects that.

**Comment by technoweenie** [comment]
@javoire You shouldn't be running `git lfs clean` or `git lfs smudge` manually.  Those are plumbing commands that expect STDIN.  In fact, you can see how the filters work by piping content into it.

```
$ cat some-big-file.whatever | git lfs clean
version https://git-lfs.github.com/spec/v1
oid sha256:34e9c5165a9714a5f850d60f4caf7f62de7d435185b4fc9f615ac529b2197877
size 20001
```

I opened #210 to fix the hanging issue.

**Comment by javoire** [comment]
gotcha :) thx for the help!
