### ISSUE TITLE
Allow 1 round-trip version of GET?

### ISSUE THREAD

**Issue by jeffhostetler** [github/git-lfs#273]
Currently to fetch a LFS file, we make a GET request using the API accept-header to get the "download" parameters and then make a second GET request (to the same or possibly a different server) to get the actual blob.  This workflow is needed when the blobs are stored on a different server (say, in S3) than where the meta data is stored.

But when the same server stores both, the server sees twice the request volume.

Does the spec and/or client code allow it to send BOTH accept-headers in the initial GET request?  Such that if the server does have both, it can return the blob immediately.

For large repos with thousands of LFS media files, this could be a significant savings, both in wall-clock time and server load.

**Comment by technoweenie** [comment]
Interesting idea.  I'm not sure it'll help much since `git` runs `git lfs smudge` one at a time as files are checked out to the working directory.  

We're leaning towards bulk download and upload endpoints.  A client could request to download 50 objects per API call, and then download the files from the storage server in parallel.  Though this isn't possible with `git lfs smudge` either.  

> Does the spec and/or client code allow it to send BOTH accept-headers in the initial GET request? Such that if the server does have both, it can return the blob immediately.

No, but I think that's a good idea.

**Comment by technoweenie** [comment]
Closing this. Good idea, but doesn't seem to be a lot of interest in it now.
