### ISSUE TITLE
Malformed "Accepts" header sent from client

### ISSUE THREAD

**Issue by feldan** [github/git-lfs#367]
I noticed that the client sends a malformed "Accepts" header (possibly others?) that can cause an unsuspecting endpoint to fail.
from the git call (with GIT_CURL_VERBOSE on):

> GET /user/repo/objects/5c659357aab447069a330ef8680ddb1e02433f8caf6d5e0b83e3ea00332ddef2 HTTP/1.1
> User-Agent: git-lfs/0.5.1 (GitHub; linux amd64; git 1.9.1; go 1.3)
> Authorization: Basic Y1Rta246cGFCc3dfcmQ=
> Accept: application/vnd.git-lfs+json; charset-utf-8

And the response (from an endpoint built with Jersey in my case):

> HTTP/1.1 400 Bad Request
> Content-Type: application/json

> {
>    "errors" : [ {
>        "status" : 400,
>        "message" : "The HTTP header field \"Accept\" with value \"application/vnd.git-lfs+json; charset-     utf-> 8\" could not be parsed."
> } ]
> }

To have it conform to the HTTP spec it should be charset=utf-8

I know it's a small thing, but it makes it hard integrating with your client (and it's a small fix) - any chance to have this in the upcoming release?
Thanks

**Comment by rubyist** [comment]
Good catch - This was fixed in https://github.com/github/git-lfs/pull/329 and will indeed be available in the next ([0.5.2](https://github.com/github/git-lfs/issues/281)) release of the client. I'm going to close this issue as it's been fixed in master. If it's blocking you, you should be OK building from master to get past it. Thanks for the report!
