### ISSUE TITLE
issue with pushing to a new branch

### ISSUE THREAD

**Issue by hszhsh** [github/git-lfs#432]
When starting a new branch and pushing it to the remote, it would transfer all the binary files again, which is very slow and is not necessary at all. I'm using v0.5.1.

**Comment by rubyist** [comment]
When pushing to the new branch, v0.5.1 will make an http call to verify each file, but if the server already has the file it will not be uploaded again. This is still not ideal because making a to verify each file is still slow, but there is work being done to reduce this to a single network call (https://github.com/github/git-lfs/pull/285) which is currently available in the latest client (but off by default) and https://github.com/github/lfs-test-server but is not yet supported on github.com.

**Comment by ttaylorr** [comment]
This has been improved dramatically since v1.2 and should no longer be an issue 😄
