### ISSUE TITLE
Intermittent error when pushing

### ISSUE THREAD

**Issue by technoweenie** [github/git-lfs#462]
https://gist.github.com/technoweenie/182d3197b22f15942a22

Fun (io?) error: `[signal 0xb code=0x1 addr=0x20 pc=0x947eb]`

Waiting on the Git LFS version...

**Comment by rubyist** [comment]
I'm thinking the problem is [here](https://github.com/github/git-lfs/blob/96c94aac6bca8cc73793660244f52b0a08dfef19/lfs/client.go#L346). We're reading from `res.Body` whether `doHttpRequest()` returns an error or not. There's probably a scenario where the HTTP request fails, leaving the response body `nil`.

**Comment by technoweenie** [comment]
Oh, good call. So I think I started the pattern of reading the extra request body to `ioutil.Discard` so that the keep-alive connection can get released back to the pool. But if there's an error, it gets released anyways.
