### ISSUE TITLE
Voodoo diffs for lfs files

### ISSUE THREAD

**Issue by eddybox** [github/git-lfs#741]
I'm working on a unity project with a collaborator. I'm on Mac, they're on Windows. We're using lfs for .unity files amongst others. We both have the following line in our .gitattributes files.

*.unity filter=lfs diff=lfs merge=lfs -text

When I check in a file, he can't open it. (Unity throws a "version error".) But if I send him the file by email, he can open it just fine.
When he checks in a file, I see it as auto-modified in git after I pull. (With Unity closed.) Trying to discard local changes on the file (ie. git checkout -- [filename]) has no effect. So git seems to be modifying it, possibly due to crlf masharlling (even with the -text setting), but I'm not sure.

Note that if I temporarily comment out the above line in my .gitattributes file, the auto-modified .unity files no longer appear as modified (no longer appear in git status). When I uncomment the line back in the files don't reappear as modified.

Hard to work this way! Is there a bug in lfs diffs? Differences between Mac and Windows versions? Settings issue...?

Thanks for your help!

Eddy

**Comment by sinbad** [comment]
Are your Unity settings set to text-based project files rather than binary project files? Right now LFS has no support for line ending conversions, so if you commit a text format Unity project file on your Mac, someone on Window will receive it verbatim (as it is on your disk) which probably means LF line endings which may well be causing the Windows Unity parser to reject it. When the reverse happens you probably just get extra CRs in the file which is why it shows up as modified. Uncommenting the filter line probably makes git do the default line-ending conversion for non-LFS which then shows up as non-modified - why it doesn't go back again might be down to status caching rather than it actually being resolved.

So right now if you need line-ending conversions in your files you can't use Git LFS to manage them without having this issue. This should be an item on the roadmap - if you agree that this sounds like your issue, please can you change the title of this issue to something like "LFS doesn't handle line ending conversions" and maybe @technoweenie or @rubyist can add the roadmap tag.

**Comment by SteveSwink** [comment]
Hey hey above-mentioned collaborator here...

So our Asset Serialization is set to the default (Mixed) right now. I'm pretty sure the result of that is .unity files and external assets (obj, psd etc...) are saved binary while scripts are text. If I switch it to text only the unity scene files triple in size.

I have a suspicion that Unity defaulting to use Visual Studio in the latest release (5.2.1) is causing a slew of line ending changes. I have been getting warnings about that when I open scripts. I don't see any such warnings when opening scene files in unity but I'm not sure where such a warning would show up. So, possibly some more data there. 

But we're definitely not using Text asset serialization on either end...

Thanks for looking into this with us :)

**Comment by eddybox** [comment]
A bit more info: I checked in a .unity scene that was 2.9MB, but when Steve checked it out it showed up on his drive at ~100KB. That's some serious decimation. Also, if Steve downloads the file directly from the github web interface he can open it just fine.

**Comment by sinbad** [comment]
> So our Asset Serialization is set to the default (Mixed) right now

So that's my theory out the window then :)

> A bit more info: I checked in a .unity scene that was 2.9MB, but when Steve checked it out it showed up on his drive at ~100KB.

Woah. What happens if you do a fresh clone on your Mac, does the same thing happen?

**Comment by eddybox** [comment]
Steve and I each did a fresh clone to our machine over the last 24 hrs; mine was fine, his got the same result: 1kb! (Mistake in my previous comment, it wasn't 100kb, it was 1.)

Browsing github the file appears to be about 2.73mb, and we can both download it fine. Git definitely seems to be doing something quite drastic to the file when pulling it in.

**Comment by sinbad** [comment]
OK so it does seem specific to the Windows version then. I've been doing some work to start getting the integration tests working on Windows, I'll see if I can reproduce this with a test repo.

**Comment by sinbad** [comment]
All seems well on Windows here. So actually I think this is much simpler; those 1k files, do they contain something like this?
```
version https://git-lfs.github.com/spec/v1
oid sha256:63ffb86c8c88e2e4857dc754c4b0ca1e8fe9ec697e0853fe8a3c89760dbfadab
size 1356
```
If so, it probably means Steve has never run `git lfs init` on his machine, so the filters that usually download the *actual* LFS content aren't running so he's just getting what's stored in git itself. It also means that whenever he's been committing new versions, they haven't been going into LFS, they've been embedded in the git repo directly. 

Many commands like `git lfs track` actually do the `init` for you so you might not realise that this is a step, but if Steve has never run any of these commands and is just using standard git commands then the global filters would be missing. We probably need to document this better.

**Comment by eddybox** [comment]
Thanks, Sinbad! Things *were* working for us for months (sharing files through lfs just fine), and Steve does still have all the proper settings in his local .gitattributes file (we share this via the repo), but I suspect you're right about the file contents. We'll talk today and dig in, but I suspect his git lfs installation has gotten trashed somehow. More soon...

**Comment by SteveSwink** [comment]
Hey so I'm now getting this error in Sourcetree:

http://prntscr.com/8t2mxr

I re-downloaded Git and Git LFS and installed but I'm still seeing my git version as 1.9.5 so I'm not sure what the heck is going on. Is there something special I have to do to update my git version?

**Comment by sinbad** [comment]
> and Steve does still have all the proper settings in his local .gitattributes file (we share this via the repo)
Yeah the trouble is that the filter that causes git to call LFS has to be configured in your global `.gitconfig` at least once, `git lfs init` will do that. 

@SteveSwink so this means you have the filter enabled now (yay) but that SourceTree can't see it. The easiest way to resolve this is to go into Tools > Options > Git, and click "Use System Git". That should pick up where you've installed the latest Git, which should *also* be the location where git-lfs.exe has been installed. If you were already using the system git then it might be that your system git has moved (latest versions of Git on Windows did that recently). So click on "Use Embedded Git" then "Use System Git" again and it should automatically find the new location; the version should be correct and then git-lfs should be found in the same location. 

FYI if you ever want to use a custom version of git-lfs you just have to uninstall the regular version and put the containing folder of git-lfs.exe on your PATH. This is how I run in Windows since I'm running the latest from source and this works with SourceTree too (you might just have to restart it after updating your PATH).

It's a bit of a hack right now, SourceTree will bundle a version of git-lfs just like git in future.
