### ISSUE TITLE
Inconvenients uploading proyect

### ISSUE THREAD

**Issue by edwinb24** [github/git-lfs#849]
I'm having difficulties syncing the files in my Flash-Portfolio-Project repository from my PC. I am currently troubleshooting the difficulty using a repository I created called Testing. Attach is some screenshots of everything I have attempt so far. First, I attempt to upload the documents like I always do with the graphic interface and receive the message in the image attach, I went ahead and attempt to check the status through Git Shell and everything seems Ok until I try to Push my files. There I have the error in the attachment. I went ahead and follow the process to install git lfs, through downloading it and running the command "git lfs install" in my git Bash and receive the message in the last attachment. I would really appreciate some assistance in the topic. Thanks in advance for any help! Have a great weekend!
P.S. If you require the files I am attempting to upload you can find them in the following link: 
https://www.dropbox.com/sh/yjwleo1r3zgk38o/AAD5_92hTUFDOmVzbLxReQF_a?dl=0

![error 3](https://cloud.githubusercontent.com/assets/14187141/11302893/6bac63da-8f65-11e5-99b5-2ccdac4a597f.png)
![error 4](https://cloud.githubusercontent.com/assets/14187141/11302891/6bab6cc8-8f65-11e5-98da-f14b47269931.png)
![error2](https://cloud.githubusercontent.com/assets/14187141/11302892/6bac3c98-8f65-11e5-8197-65c4a8c1ffbe.png)

**Comment by technoweenie** [comment]
@edwinb24 In the first screenshot, you're not using Git LFS. GitHub rejects single files over 100MB on push. For GitHub to accept the file, you'll have to remove the big files first. 

Git LFS is an alternative. However, simply installing it will not rewrite your repository for you. If you have an existing repository, [BFG Repo Cleaner](https://github.com/rtyley/bfg-repo-cleaner/releases) is a great way to migrate the files. 

Since you have GitHub Desktop installed, using Git LFS should be really easy for a new repository. It has a Git LFS section in Repository Settings that you can use. Just add the file extensions (like `*.zip`) for big files that you want to track in Git LFS. Doing this properly will let you push to GitHub.

![windows_10_x64_base](https://cloud.githubusercontent.com/assets/21/11303703/75570a88-8f61-11e5-90ba-fc009093de8f.png)

**Comment by edwinb24** [comment]
Thanks a @technoweenie. I will give it a shot and let you know how it goes. Do you know what is the limit size for a file in GitHub before you need to use LFS?

**Comment by technoweenie** [comment]
GitHub will warn you if you have single files over 50MB. It rejects pushes with files over 100MB. Git LFS supports files up to 2GB.

Thanks for checking Git LFS out!
