### ISSUE TITLE
LFS issue with S3

### ISSUE THREAD

**Issue by DarkShear** [github/git-lfs#897]
My organisation has been using git lfs for several months by and large without too many problems. Our git lfs clients are all 0.5.x (pre-batch API) and we wrote our own git lfs server that provides the git lfs client with signed URLs to store and retrieve the binary files to/from S3.

I am now in the process of trying to upgrade us to the latest git lfs version, v 1.1.0 but am encountering some problems that I can't seem to make any headway with.

I have updated our git lfs server to support the batch API and it successfully returns the signed S3 upload URLs for multiple objects. However after receiving the batch API response my git client insists in  pausing and prompting for a username and password for each file to be uploaded. I can happily enter nothing for both username and password and the upload will continue and complete successfully.

If I do exactly the same thing except proxy the upload via my git lfs server (so the git lfs client doesn't directly talk to S3) it works fine and it also worked fine with git lfs 0.5.x.

The same thing also happens with downloads:

![gitscreen](https://cloud.githubusercontent.com/assets/13421866/11810998/6e8b5560-a32a-11e5-9bd6-20ec649e228e.PNG)

Is there an obvious solution to this problem? Let me know what I can do to help track it down.

I am on Windows 7 using msysgit version 1.9.5.

**Comment by technoweenie** [comment]
Hi, I'm going through old issues that I've missed and replying to them.

I think the problem is that the LFS client thinks those urls are not authenticated, since the batch api is not returning an `Authorization` header. The current ugly solution is to tack on `&token=1` to your generated S3 urls. There's some discussion of this in https://github.com/github/git-lfs/issues/1088, and a proposal to change this in https://github.com/github/git-lfs/issues/960 in the future.
