### ISSUE TITLE
Not really an issue, more like advice request

### ISSUE THREAD

**Issue by bertalanimre** [github/git-lfs#954]
Hello People!

Can I ask what would you do in my position? 
let's say you have a very important webserver that has to go 0/24, 7/7, etc. And you have a website that is normally very small but had to add a few big files like mp4, mov. And now, a few commits and one month later the space is running low on the server. The reason is: .git folder is inceasing due to the mp4 and mov files. I wish to use LFS from now on on all developement machines and the server but I have to reduce the size of the /var/www folder as well.

How about this:
I simply make a git clone to a 3rd computer that has Git LFS installed. I add the mp4 and mov files to track. Meanwhile on the server I completly remove the whole folder of the website and then install git LFS. After these all, I push back the website from the 3rd computer, and pull the new commit to the server. Would it contain the video files as well and since LFS is installed and in the future only point to them not freating huge objects inside .git folder?

Or am I completly wrong? Please assist.

Bert

**Comment by technoweenie** [comment]
You're correct that using Git LFS means that the bare git repository will be smaller, since the video files won't be included. However, when Git LFS checks the files out it stores the objects in `.git/lfs/objects` AND in the working directory. There is a [`prune` command](https://github.com/github/git-lfs/blob/master/docs/man/git-lfs-prune.1.ronn) that can clean older versions up based on local git config settings. But, you'll still be using about 2x the space with Git LFS currently.

**Comment by technoweenie** [comment]
Closing this, feel free to re-open if you have any other questions/comments.
