### ISSUE TITLE
empty/malformed manpages when installed via deb

### ISSUE THREAD

**Issue by whitty** [github/git-lfs#995]
Installed from the packagecloud location on ubuntu trusty the man-pages are malformed or empty - note only 20 bytes long:

```
$ ls -l /usr/share/man/man1/git-lfs*
-rw-r--r-- 1 root root 20 Feb  6 05:34 /usr/share/man/man1/git-lfs.1.gz
-rw-r--r-- 1 root root 20 Feb  6 05:34 /usr/share/man/man1/git-lfs-checkout.1.gz
-rw-r--r-- 1 root root 20 Feb  6 05:34 /usr/share/man/man1/git-lfs-clean.1.gz
-rw-r--r-- 1 root root 20 Feb  6 05:34 /usr/share/man/man1/git-lfs-env.1.gz
-rw-r--r-- 1 root root 20 Feb  6 05:34 /usr/share/man/man1/git-lfs-ext.1.gz
-rw-r--r-- 1 root root 20 Feb  6 05:34 /usr/share/man/man1/git-lfs-fetch.1.gz
-rw-r--r-- 1 root root 20 Feb  6 05:34 /usr/share/man/man1/git-lfs-fsck.1.gz
-rw-r--r-- 1 root root 20 Feb  6 05:34 /usr/share/man/man1/git-lfs-init.1.gz
-rw-r--r-- 1 root root 20 Feb  6 05:34 /usr/share/man/man1/git-lfs-install.1.gz
-rw-r--r-- 1 root root 20 Feb  6 05:34 /usr/share/man/man1/git-lfs-logs.1.gz
-rw-r--r-- 1 root root 20 Feb  6 05:34 /usr/share/man/man1/git-lfs-ls-files.1.gz
-rw-r--r-- 1 root root 20 Feb  6 05:34 /usr/share/man/man1/git-lfs-pointer.1.gz
-rw-r--r-- 1 root root 20 Feb  6 05:34 /usr/share/man/man1/git-lfs-pre-push.1.gz
-rw-r--r-- 1 root root 20 Feb  6 05:34 /usr/share/man/man1/git-lfs-prune.1.gz
-rw-r--r-- 1 root root 20 Feb  6 05:34 /usr/share/man/man1/git-lfs-pull.1.gz
-rw-r--r-- 1 root root 20 Feb  6 05:34 /usr/share/man/man1/git-lfs-push.1.gz
-rw-r--r-- 1 root root 20 Feb  6 05:34 /usr/share/man/man1/git-lfs-smudge.1.gz
-rw-r--r-- 1 root root 20 Feb  6 05:34 /usr/share/man/man1/git-lfs-status.1.gz
-rw-r--r-- 1 root root 20 Feb  6 05:34 /usr/share/man/man1/git-lfs-track.1.gz
-rw-r--r-- 1 root root 20 Feb  6 05:34 /usr/share/man/man1/git-lfs-uninit.1.gz
-rw-r--r-- 1 root root 20 Feb  6 05:34 /usr/share/man/man1/git-lfs-uninstall.1.gz
-rw-r--r-- 1 root root 20 Feb  6 05:34 /usr/share/man/man1/git-lfs-untrack.1.gz
-rw-r--r-- 1 root root 20 Feb  6 05:34 /usr/share/man/man1/git-lfs-update.1.gz
```

How to reproduce:

```
$ cat /etc/apt/sources.list.d/git-lfs.list 
# this file was generated by packagecloud.io for
# the repository at https://packagecloud.io/github/git-lfs

deb https://packagecloud.io/github/git-lfs/ubuntu/ trusty main
deb-src https://packagecloud.io/github/git-lfs/ubuntu/ trusty main
$ apt-get install git-lfs
$ ls -l /usr/share/man/man1/git-lfs*
```

Presumably the packaging scripts are broken.

**Comment by Vdragon** [comment]
I have the same issue, all manpages tarballs are 20 bytes.

**Comment by andyneff** [comment]
Ok. It boils down to the dh_installman command. It Works if the PATH is normal. But when running `dpkg-buildpackage`, the path is PREPENDED by the obj directory, `/tmp/docker_run/git-lfs/obj-x86_64-linux-gnu/bin`... which breaks it... 

Debian "helper" decides it wants to compile EVERYTHING it can get its dirty hands on (instead of calling bootstrap)... So in Debian's infinite wisdom, it creates a `script` binary and `man` binary. (I suspect due to  `docs/man/mangen.go` and `script/script.go`... if I had to CONTINUE guessing, it is named after the directory name, not the gofile name...)

So I got two ideas in mind. 

1. Change `override_dh_auto_build` to delete the binary name I know is causing the problem, `man`. I'm not thrilled about this because what happens when the stars align and add yet ANOTHER file?

		override_dh_auto_build:
			dh_auto_build
			#dh_golang doesn't do anything here in deb 8, and it's needed in both  
			if [ "$(DEB_HOST_GNU_TYPE)" != "$(DEB_BUILD_GNU_TYPE)" ]; then\
				cp -rf $(BUILD_DIR)/bin/*/* $(BUILD_DIR)/bin/; \
				cp -rf $(BUILD_DIR)/pkg/*/* $(BUILD_DIR)/pkg/; \
			fi
			rm $(BUILD_DIR)/bin/script
			rm $(BUILD_DIR)/bin/man
			./script/man

2. Change `override_dh_auto_build` to call bootstrap instead of dh_auto_build

		override_dh_auto_build:
			./script/bootstrap
			mkdir -p $(BUILD_DIR)/bin
			cp -rf ./bin/* $(BUILD_DIR)/bin/
			./script/man

Both fix the problem. Which do you think is better, @ssgelm?

**Comment by ssgelm** [comment]
Thanks for looking into this - it was on my todo list but I have been busy.  That's a tough call.  Neither option is ideal.  I think I'd say option 1 is better because it follows more of the debian style?

**Comment by whitty** [comment]
Thanks - I hadn't checked for when this was released but its definitely fixed for 1.2.1

**Comment by Vdragon** [comment]
I can confirm the manpages are accessible on current status.  The issue shall no longer needed to be open.

**Comment by andyneff** [comment]
Thanks all!
